# Generated by Django 4.0.1 on 2022-02-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shawarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('working_status', models.CharField(max_length=50)),
                ('location_iframe', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[(1, 'Мерзко'), (2, 'Невкусно'), (3, 'Нормально'), (4, 'Вкусно'), (5, 'Очень вкусно')], max_length=200)),
                ('comment', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shawarma_app.shawarma')),
            ],
        ),
    ]
