# Generated by Django 4.0.1 on 2022-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shawarma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shawarma',
            name='standart_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
